- name: Deploy browserless
  hosts: all
  tasks:
    - name: Copy application's stack file
      ansible.builtin.template:
        src: "{{inventory_dir}}/stack.yml"
        dest: "/tmp/{{application_name}}.yml"
    - name: Deploy stack from a compose file
      docker_stack:
        state: present
        name: "{{application_name}}"
        compose:
          - "/tmp/{{application_name}}.yml"
