version: "3.2"

services:
  browserless:
    image: "browserless/chrome:latest"
    environment:
      MAX_CONCURRENT_SESSIONS: 10
    ports:
      - "3000:3000"
  application:
    image: "ghcr.io/rukomoynikov/screenshoter"
    ports:
      - "8080:8080"
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.application.rule=Host(`screenshoter.codemetrics.dev`)
        - traefik.http.routers.application.tls=true
        - traefik.http.routers.application.tls.certresolver=leresolver
        - traefik.http.routers.application.middlewares=redirect-to-https
        - traefik.http.routers.application-https.rule=Host(`screenshoter.codemetrics.dev`)
        - traefik.http.routers.application-https.entrypoints=websecure
        - traefik.http.routers.application-https.tls=true
        - traefik.http.routers.application-https.tls.certresolver=le
        - traefik.http.routers.application-https.middlewares=redirect-to-https
        - traefik.http.routers.application-https.service=application
        - traefik.http.services.application.loadbalancer.server.port=8080

networks:
  traefik-public:
    external: true