version: "3.2"

services:
  browserless:
    image: "browserless/chrome:latest"
    environment:
      MAX_CONCURRENT_SESSIONS: 10
    ports:
      - "3000:3000"
  application:
    image: "ghcr.io/rukomoynikov/cover_image"
    ports:
      - "8080:8080"