version: "3.2"

services:
  browserless:
    image: "browserless/chrome:latest"
    networks:
      - app-network
    environment:
      MAX_CONCURRENT_SESSIONS: 20
    ports:
      - "3000:3000"
  application:
    image: "ghcr.io/rukomoynikov/screenshoter"
    ports:
      - "8080:8080"
    networks:
      - traefik-public
      - app-network
      - logs_default
#    logging:
#      driver: "gelf"
#      options:
#        gelf-address: "udp://logs_seq-input-gelf:12201"
#        tag: "screenshoter"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.screenshoter.rule=Host(`screenshoter.codemetrics.dev`)
        - traefik.http.routers.screenshoter.tls=true
        - traefik.http.routers.screenshoter.tls.certresolver=leresolver
        - traefik.http.routers.screenshoter.middlewares=redirect-to-https
        - traefik.http.routers.screenshoter-https.rule=Host(`screenshoter.codemetrics.dev`)
        - traefik.http.routers.screenshoter-https.entrypoints=websecure
        - traefik.http.routers.screenshoter-https.tls=true
        - traefik.http.routers.screenshoter-https.tls.certresolver=leresolver
        - traefik.http.routers.screenshoter-https.middlewares=redirect-to-https
        - traefik.http.routers.screenshoter-https.service=screenshoter
        - traefik.http.services.screenshoter.loadbalancer.server.port=8080

networks:
  traefik-public:
    external: true
  app-network:
    driver: overlay
    internal: true
    attachable: true
  logs_default:
    external: true