name: Docker Image CI

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: screenshoter
          file: screenshoter/Dockerfile-production
          push: true
          tags: |
            ghcr.io/rukomoynikov/screenshoter:latest
            ghcr.io/rukomoynikov/screenshoter:${{ github.sha }}
            
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Create and populate ansible inventory file
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          IP_ADDRESS: ${{ secrets.IP_ADDRESS }}
        run: |
          cat <<EOF > deploy/hosts.json
          {
            "all": {
              "hosts": {
                "production": {
                  "ansible_host": "$IP_ADDRESS",
                  "ansible_user": "root"
                }
              },
              "vars": {
                "application_name": "browserlessio",
                "GITHUB_TOKEN": "$GHCR_TOKEN",
              }
            }
          }
          EOF
          
          cat deploy/hosts.json
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy_app.yml
          directory: ./deploy
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --inventory hosts.json
            --verbose            

